version: "3.9"

services:
  registry:
    image: registry:2
    container_name: katy-registry
    ports:
    - "5000:5000"
    restart: unless-stopped
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
    volumes:
      - ./data/registry:/var/lib/registry
      - ./auth/htpasswd:/auth/htpasswd:ro
      - ./registry/config.yml:/etc/docker/registry/config.yml:ro
    networks:
      - admin_proxy         
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.registry.rule=Host(`registry.master-pr-katy.a3n.fr`)"
      - "traefik.http.routers.registry.entrypoints=websecure"
      - "traefik.http.routers.registry.tls=true"
      - "traefik.http.routers.registry.tls.certresolver=letsencrypt"
      - "traefik.http.services.registry.loadbalancer.server.port=5000"
      - "traefik.http.routers.registry.middlewares=registry-ratelimit@docker"
      - "traefik.http.middlewares.registry-ratelimit.ratelimit.average=20"
      - "traefik.http.middlewares.registry-ratelimit.ratelimit.burst=50"

  registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: katy-registry-ui
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - REGISTRY_TITLE=Registry-Privé
      - REGISTRY_URL=https://registry.master-pr-katy.a3n.fr
      - DELETE_IMAGES=true
      - NGINX_PROXY_PASS_URL=https://registry.master-pr-katy.a3n.fr
      - SINGLE_REGISTRY=true
    networks:
      - admin_proxy
    depends_on:
      - registry
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.registry-ui.rule=Host(`registry-ui.master-pr-katy.a3n.fr`)"
      - "traefik.http.routers.registry-ui.entrypoints=websecure"
      - "traefik.http.routers.registry-ui.tls=true"
      - "traefik.http.routers.registry-ui.tls.certresolver=letsencrypt"
      - "traefik.http.services.registry-ui.loadbalancer.server.port=80"

networks:
  admin_proxy:
    external: true    